global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
        labels:
          service: 'maplayer-backend'
    metrics_path: /metrics
